#!/bin/bash -
#title          :replicationzfs
#description    :This script copy all data with ZFS send and rsync
#author         :Lucas Dousse
#date           :20170512
#version        :1.1.4
#usage          :./replicationzfs
#notes          :
#bash_version   :4.3.46(1)-release
#============================================================================


# Logger
exec 1> >(logger -s -t $(basename $0)) 2>&1

#####################
#     VARIABLES     #
#####################
srv_dest="srv-tpi-ldo-02.dsprod.ch" # Serveur de destination

src_pool="zroot"      				# Pool ZFS de départ
dest_pool="zroot/new"				# Pool ZFS de réception sur le serveur distant

snap_prefix="today_" 				# Préfix pour le nom du snapshot
snap_time=$(date '+%H')  			# Timestamp for snapshot
snap_time_old=0
let "snap_time_old=$snap_time-1"
snap_new="$src_pool"@"$snap_prefix""$snap_time"  		# Forge du nom du nouveau snapshot

################
#     TEST     #
################
if [ $snap_time_old -lt 10 ] 		# Test si l'heure et inférieur a 10 heure alors 0X
then
    snap_time_old=0"$snap_time_old"
fi

if [ $snap_time == 00 ] 		# Test si l'heure et inférieur a minuit alors 23
then
    snap_time_old=23
fi

snap_old="$src_pool"@"$snap_prefix""$snap_time_old" 	# Forge du nom de l'ancien snapshot


#####################
#     FUNCTIONS     #
#####################
function zfs_snap() {  							# Fonction de départ qui crée le snapshot et vérifie que il existe un plus vieux pour faire de l'incrémental
	zfs snapshot -r "$snap_new" 						# Create the snapshot
	zfs list -t snapshot > /tmp/snapshot.txt			# Export de la liste des snapshot

	if grep -Fq "$snap_new" /tmp/snapshot.txt 			# Si | test si le nouveau snapshot a été fait
		then
		echo "[ OK ] New snapshot exist !" 
		if grep -Fq "$snap_old" /tmp/snapshot.txt 		# Si | test si le snapshot vieux de 1 heure existe
			then
			echo "[ OK ] Older 1 hour snapshot exist !"
			rm -rf /tmp/snapshot.txt
			zfs_send 									# Si oui | Il va aller dans la fonction zfs_send, afin de faire de l'incrementiel
		else 									
			echo "[ WARNING ] Older 1 hour snapshot don't exist !"
            rm -rf /tmp/snapshot.txt
			zfs_send_first 								# Si non | Il va créer le premier backup full
		fi
	else
		echo "[ ERROR ] unknown"
		rm -rf /tmp/snapshot.txt
		exit -1;
	fi
}

function zfs_send_first() {  					# Fonction de backup full avec zfs send
	echo "[ INFO ] Starting sending first snapshot..."
	zfs send "$snap_new" | ssh "$srv_dest" zfs recv "$dest_pool"  	# Envoie tout le contenu sur le serveur distant en un bloc
	zfs_control_recv
}

function zfs_send() { 							# Fonction de backup incrementiel avec zfs send
	echo "[ INFO ] Starting sending incremental snapshot..."
	zfs send -R -i  "$snap_old" "$snap_new" | ssh "$srv_dest" zfs recv "$dest_pool" # Envoie le diff du vieux snapshot sur le nouveaux serveur
	zfs_control_recv
}

function zfs_control_recv() { 					# Fonction de control que le snapshot envoyer aie bien été reçu de l'autre coté
	ssh "$srv_dest" 'zfs list -t snapshot > /tmp/snapshot.txt'
	ssh "$srv_dest" 'if grep -Fq "$snap_new" /tmp/snapshot.txt; then echo "[ OK ] destination have good receive snapshot !"; else exit -1; fi'
	ssh "$srv_dest" 'rm -rf /tmp/snapshot.txt'
	send_xml
}

function send_xml() { 							# Fonction d'envoie des fichier de config des vm
	echo "[ INFO ] Sending xml files for KVM..."
	rsync -ra /etc/libvirt/qemu/ "$srv_dest":/etc/libvirt/qemu/
	modifiaction_xml
}

function modifiaction_xml() { 					# Modification des xml, car nouveau chemin n'est pas le meme que l'ancien
	echo "[ INFO ] Modification of xml for new $dest_pool ..."
	ssh "$srv_dest" "sed -i 's/zroot/zroot\/new/g' /etc/libvirt/qemu/*.xml"
	restart_kvm
}

function restart_kvm() { 						# Fonction de restart de kvm afin de prendre en compte les modifs
	echo "[ INFO ] Restarting kvm for apply change..."
	ssh "$srv_dest" service libvirt-bin restart
	del_old_snap
}

function del_old_snap() {
	zfs list -H -t snapshot -o name -S creation | sed '1d' | sed '1d' > /tmp/snap_srv1.txt  # Liste les snapshot et supprime les 2 derniers du fichiers
	ssh "$srv_dest" "/usr/bin/delOldSnap" 						# Execution du script sur le server distant

	if [[ -s /tmp/snap_srv1.txt ]]; then 						# Test si le fichier n'est pas vide
		while IFS='' read -r line || [[ -n "$line" ]]; do  		# Boucle pour lire et supprimer les vieux snapshot
    		echo "[ INFO ] Delete: $line"
    		zfs destroy "$line"
		done < "/tmp/snap_srv1.txt"
		rm -rf /tmp/snap_srv1.txt
	else 														# Sinon ne fait rien
		echo "[ OK ] snapshot is already delete"
		rm -rf /tmp/snap_srv1.txt
		exit 0;
	fi

}

#####################
#     EXECUTION     #
#####################
zfs_snap

#################
#     UNSET     #
#################
unset snap_time_old
unset srv_dest
unset src_pool
unset dest_pool
unset snap_prefix
unset snap_time
unset snap_new
unset snap_old
